spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL_PRODUCT:jdbc:postgresql://localhost:5432/product_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  server:
    port: 9091

jwt:
  secret: ${JWT_SECRET:your-secret-key-that-is-long-enough-to-be-secure}